linters:
  enable:
    - golint
    - goimports
    - scopelint
    - gocyclo
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - varcheck
    - bodyclose
    - golint
    - misspell
    - deadcode
    - unused
  disable:
    - errcheck
run:
  deadline: 5m
